

CATALOGUE_HOST: catalogue.backend-{{ env }}.raheemweb.fun
USER_HOST: user.backend-{{ env }}.raheemweb.fun
CART: cart.backend-{{ env }}.raheemweb.fun
SHIPPING_HOST: shipping.backend-{{ env }}.raheemweb.fun
PAYMENT_HOST: payment.backend-{{ env }}.raheemweb.fun