  - name: app setup
    include_role:
      name: common
      tasks_from: app.yaml 

 
  - name: maven setup
    include_role:
      name: common
      tasks_from: maven.yaml
    
  - name: systemd setup
    include_role: 
      name: common
      tasks_from: systemd.yaml



 
