- name: disable nodejs module
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs module
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: creating system user
  ansible.builtin.user:
    name: Roboshop
    shell: /sbin/nologin
    system: true
    home: /app



- name: dependencies
  community.general.npm:
    path: /app/
