- name: app setup
  include_role:
    name: common
    tasks_from: app.yaml


- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs.yaml

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml